# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cfbfa9cbe416a497c8d62d09d50faee94fffb65e16f4c13dd03f65d7c9804060b05f4f0eb0d9877188c62da9c630939709772091bf9b564f78cf47e66fc4c9c

test:
  secret_key_base: cd8459ca64bb4e2dd83c30b610e3e855875de1ecc6c00e7c1ccb8cb9e0712f68019f632656a4dd04c6575c0d55ff3b9a65457e5941c3148583afd1c012379c6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
